config/routes.rb
Rails.application.routes.draw do
  get '/products/new', to: 'products#new', as: :new_product
  get '/products' , to: 'products#index'
  get '/products/:id' , to: 'products#show', as: :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        # Variable de instancia, se puede leer desde nuestra vista
        @products = Product.all
    end

    def show
        # Recibimos el id enviado por parámetro
        @product = Product.find(params[:id])
    end

    def new 
        @product = Product.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo | Compra y vende productos de segunda mano</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <!-- Propiedad especial que sustituye el contenido del componente , Dinámico-->
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Productos:</h1>

<% @products.each do |product| %>
    <%= link_to product_path(product.id), class: 'product' do %>
        <h2><%= product.title %></h2>
        <span>$<%= product.price %></span>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h2>Añadir producto</h2>

<%= form_with model: @product do |form| %>
    
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>    
    </div>

    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>    
    </div>

    <%= form.submit %>
<% end %>

app/views/products/show.html.erb
<h2>Título</h2>
<h3 class="title"><%= @product.title %></h3>
<h2>Descripción</h2>
<h3 class="description"><%= @product.description %></h3>
<h2>Precio</h2>
<h3 class="price"><%= @product.price %></h3>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
    <h1>Home</h1>
<% end %>
<marquee style="color: red; font-size: 50px;">Página de monas xinas 😎</marquee>
<marquee>creada con Ruby On Rails :v</marquee>

<%= link_to 'Añadir producto', new_product_path %>